# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c414d42cfee4653111ad4999bc62140ddc3b7c680772fdb57f35d1d37dcfc6831b50c32b062febc897443f24519b9778aef0e33819656daf8ff592848b0a7f0

test:
  secret_key_base: f4cf299bda4921122b175d5fd144a3ea04b916c5d1c69746584b6185bb46acabe799465f6fdf7cef0e0f58cdb0b81605d98711982fa72cb23e603fe4ac15ad32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
